-- Create services table
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create products table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert initial services
INSERT INTO services (name, price) VALUES
    ('Cabelo', 35.00),
    ('Barba', 30.00),
    ('Sobrancelhas', 10.00),
    ('Relaxamento', 25.00),
    ('Luzes', 45.00),
    ('Pigmentação', 25.00),
    ('Depilação Cera Nariz', 15.00),
    ('Maquina na barba', 10.00),
    ('Risco', 10.00);
